# Pandoc --defaults shared between Manubot output formats.
from: markdown
filters:
- pandoc-fignos
- pandoc-eqnos
- pandoc-tablenos
# - pandoc-manubot-cite
- citeproc
wrap: preserve
metadata:
  csl: config/pandoc/csl/style.csl
  link-citations: true